# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: docker:17.05.0-ce-git

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/agent

    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
        - v1-{{ .Branch }}
        paths:
        - /caches/layercache.tar
    - run:
        name: Install bash
        command: |
          set +o pipefail
          apk --no-cache update && apk --no-cache add bash
    - run:
        name: Load Docker image layer cache
        command: |
          mkdir -p /caches
          set +o pipefail
          docker load -i /caches/layercache.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWD

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            export PUSHARG=push
          else
            export PUSHARG=
          fi
          (cd agent && ./build-docker.sh ${PUSHARG})
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
        - /caches/layercache.tar
